# PeerAuthentication policy for the "store" service enforcing STRICT mutual TLS
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: store-peer-policy
  namespace: production
spec:
  selector:
    matchLabels:
      app: store
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: store-request-policy
  namespace: production
spec:
  selector:
    matchLabels:
      app: store
  jwtRules:
  - issuer: "https://your-oauth2-provider.example.com" # Replace with your OAuth2 provider's issuer URL
    jwksUri: "https://your-oauth2-provider.example.com/.well-known/jwks.json" # Replace with your OAuth2 provider's JWKS URI
    # Optionally, you can also define the audiences that should be allowed to access
    audiences:
      - "api://default" # Replace with your intended audience if needed
