# AuthorizationPolicy for allowing traffic from the "store" service to the "invoice" service in the "production" namespace
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authorization-policy-store-to-invoice  
  namespace: production                         
spec:
  selector:
    matchLabels:
      app: store  
  action: ALLOW   

  # Rule allowing GET requests to "/invoice" from the "store" service
  rules:
  - to:
    - operation:
        methods: ["GET"]
      paths: ["/invoice"]
    from:
    - source:
        labels:
          app: store

  # Rule allowing POST requests to "/invoice" from the "store" service
  - to:
    - operation:
        methods: ["POST"]
      paths: ["/invoice"]
    from:
    - source:
        labels:
          app: store
