apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: store-virtualservice
  namespace: jhipster
spec:
  hosts:
    - store
  http:
    - route:
        - destination:
            host: invoice
            subset: "v1"
          weight: 80
        - destination:
            host: invoice
            subset: "v2"
          weight: 20
        - destination:
          host: notification
          subset: "v1"
          weight: 100            
      retries:
        attempts: 3
        perTryTimeout: 2s


 
        