apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: store-network-policy
  namespace: production
spec:
  podSelector:
    matchLabels:
      app: store
  policyTypes:
    - Egress
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: invoice
    - to:
      - podSelector:
          matchLabels:
            app: notification
