# Deployment for the "store" microservice in the "production" namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      version: "v1"
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - store
                topologyKey: kubernetes.io/hostname
              # Weight for anti-affinity rule
              weight: 100
      initContainers:
        # Init container to check database connectivity before starting the main application
        - name: init-ds
          image: busybox:latest
          command:
            - "/bin/sh"
            - "-c"
            - |
              while true
              do
                # Check if the PostgreSQL database is reachable
                rt=$(nc -z -w 1 store-postgresql 5432)
                if [ $? -eq 0 ]; then
                  echo "DB is UP"
                  break
                fi
                echo "DB is not yet reachable; sleep for 10s before retry"
                sleep 10
              done
      containers:
        - name: store-app
          image: kamathadityaa/store-istio
          env:
            # Environment variables for configuring the "store" microservice
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET
              # Reference to a Kubernetes secret for JWT secret
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: SPRING_DATASOURCE_URL
              # Database connection URL
              value: jdbc:postgresql://store-postgresql.production.svc.cluster.local:5432/store
            - name: SPRING_DATASOURCE_USERNAME
              # Database username
              value: store
            - name: SPRING_R2DBC_PASSWORD
              # Reference to a Kubernetes secret for R2DBC password
              valueFrom:
                secretKeyRef:
                  name: store-postgresql
                  key: postgresql-password
            - name: SPRING_LIQUIBASE_URL
              # Liquibase database migration URL
              value: jdbc:postgresql://store-postgresql.production.svc.cluster.local:5432/store
            - name: SPRING_R2DBC_URL
              # R2DBC connection URL
              value: r2dbc:postgresql://store-postgresql.production.svc.cluster.local:5432/store
            - name: SPRING_SLEUTH_PROPAGATION_KEYS
              # Sleuth propagation keys for distributed tracing
              value: "x-request-id,x-ot-span-context"
            - name: JAVA_OPTS
              # Java options for the JVM
              value: " -Xmx256m -Xms256m"
            - name: SERVER_SHUTDOWN
              # Shutdown mode for the server
              value: graceful
          resources:
            # Resource limits and requests for the container
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            # Port configuration for the HTTP endpoint
            - name: http
              containerPort: 8080
          readinessProbe:
            # Readiness probe configuration
            httpGet:
              path: /management/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 6
          livenessProbe:
            # Liveness probe configuration
            httpGet:
              path: /management/health/liveness
              port: http
            initialDelaySeconds: 100

