# PeerAuthentication policy to enforce mTLS for the "store" service
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: store-peer-policy
  namespace: production
spec:
  selector:
    matchLabels:
      app: store 
  mtls:
    mode: STRICT  # Enforces mTLS for all incoming connections

---
# RequestAuthentication policy for JWT validation for the "store" service
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: store-request-policy
  namespace: production
spec:
  selector:
    matchLabels:
      app: store 
  jwtRules:
  - issuer: "https://your-oauth2-provider.example.com" # Replace with your OAuth2 provider's issuer URL
    jwksUri: "https://your-oauth2-provider.example.com/.well-known/jwks.json" # JWKS URI of the OAuth2 provider

    
