# Secret for PostgreSQL database credentials used by the "store" service
apiVersion: v1
kind: Secret
metadata:
  name: store-postgresql
  namespace: production
  labels:
    app: store-postgresql
type: Opaque
data:
  postgresql-password: ZjA4MjI3MDI0ZmU2OWQzOWVkM2U2YWM3ODliOTVlYTRlYmE1MzhiYjFjMDI0MTUwYWVkNTg3MmNiZDE4
---
# Deployment configuration for the PostgreSQL database used by the "store" service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-postgresql
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-postgresql
  template:
    metadata:
      labels:
        app: store-postgresql
      annotations:
        # Annotation to disable Istio sidecar injection for this pod
        sidecar.istio.io/inject: "false"
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: store-postgres-pvc
      containers:
        - name: postgres
          image: postgres:14.2
          env:
            - name: POSTGRES_USER
              value: store
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: store-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - store
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - store
            initialDelaySeconds: 5
            periodSeconds: 10
---
# PersistentVolumeClaim for PostgreSQL data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: store-postgres-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# Service configuration for the PostgreSQL database used by the "store" service
apiVersion: v1
kind: Service
metadata:
  name: store-postgresql
  namespace: production
spec:
  selector:
    app: store-postgresql
  ports:
    - port: 5432
