# Istio Gateway configuration for the "store" service
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: store-gateway
  namespace: production
  labels:
    gateway: store-gateway
    istio: ingressgateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - store.jhipster.34.76.233.160.nip.io
    - port:
        number: 80
        name: http2
        protocol: HTTP2
      hosts:
        - store.jhipster.34.76.233.160.nip.io
---
# Istio VirtualService configuration for the "store" service
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  # Name and namespace of the VirtualService
  name: store-virtualservice
  namespace: jhipster
  labels:
    service: store-virtualservice
spec:
  hosts:
    # Hostname for the VirtualService
    - store.jhipster.34.76.233.160.nip.io
  gateways:
    - store-gateway
  http:
    - match:
        # Match criteria based on URI and user-agent header
        - uri:
            prefix: /
          headers:
            user-agent:
              regex: ".*Chrome"
      route:
        # Route traffic to version "v2" of the "store" service subset
        - destination:
            host: store
            subset: v2
      fault:
        # Introduce fault for 50% of the matched traffic
        delay:
          percent: 50
          fixedDelay: 10s
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: store
            subset: v1
      fault:
        abort:
          percentage:
            value: 50
          httpStatus: 500
    - match:
        - uri:
            prefix: /services/invoice/
      rewrite:
        uri: /
      route:
        - destination:
            host: invoice
    - match:
        - uri:
            prefix: /services/notification/
      rewrite:
        uri: /
      route:
        - destination:
            host: notification
    - match:
        - uri:
            prefix: /services/product/
      rewrite:
        uri: /
      route:
        - destination:
            host: product
    - route:
        - destination:
            host: store
