apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: store-policy
  namespace: production # Replace with your store service's namespace
spec:
  selector:
    matchLabels:
      app: store  
  action: ALLOW
  rules:
  # Rule to allow traffic from Istio ingress gateway to the store service
  - from:
    - source:
        principals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"]

  # Rule to restrict access to specific paths in the store service
  - to:
    - operation:
        methods: ["GET", "POST"]
        paths: ["/some/specific/path", "/another/path"]
