apiVersion: v1
kind: Secret
metadata:
  name: grafana-certificate
  namespace: istio-system
type: kubernetes.io/tls
data:
  tls.crt: |
    BASE64_ENCODED_CERTIFICATE_CONTENT  # Replace with actual certificate content
  tls.key: |
    BASE64_ENCODED_PRIVATE_KEY_CONTENT  # Replace with actual private key content

---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: grafana-observability-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - grafana.istio-system.34.76.233.160.nip.io
    tls:
      mode: SIMPLE
      credentialName: grafana-certificate  # Adjust to match the Secret name

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana-virtualservice
  namespace: istio-system
spec:
  hosts:
    - grafana.istio-system.34.76.233.160.nip.io
  gateways:
    - grafana-observability-gateway  # Adjust to match the Gateway name
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: grafana
        port:
          number: 3000
