apiVersion: v1
kind: Secret
metadata:
  name: grafana-certificate
  namespace: istio-system
type: kubernetes.io/tls
data:
  tls.crt: |
    BASE64_ENCODED_CERTIFICATE_CONTENT
  tls.key: |
    BASE64_ENCODED_PRIVATE_KEY_CONTENT
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: grafana-observability-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - grafana.istio-system.34.76.233.160.nip.io
    tls:
      mode: SIMPLE
      credentialName: grafana-observability-certificate
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana-virtualservice
  namespace: istio-system
spec:
  hosts:
    - grafana.istio-system.34.76.233.160.nip.io
  gateways:
    - grafana-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: grafana
        port:
          number: 3000
