apiVersion: v1
kind: Secret
metadata:
  name: kiali-certificate
  namespace: istio-system
type: kubernetes.io/tls
data:
  tls.crt: |
    BASE64_ENCODED_CERTIFICATE_CONTENT
  tls.key: |
    BASE64_ENCODED_PRIVATE_KEY_CONTENT

---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: kiali-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - kiali.istio-system.34.76.233.160.nip.io
      tls:
        mode: SIMPLE
        credentialName: kiali-certificate        
    - port:
        number: 80
        name: http2
        protocol: HTTP2
      hosts:
        - kiali.istio-system.34.76.233.160.nip.io
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kiali-virtualservice
  namespace: istio-system
spec:
  hosts:
    - kiali.istio-system.34.76.233.160.nip.io
  gateways:
    - kiali-gateway
  http:
    - route:
        - destination:
            host: kiali
            port:
              number: 20001